---
version: "2.1"
services:
  devlength:
    image: dev_length:minimal
    container_name: devlength
    #ports:
    #  - 9000:8501
    restart: unless-stopped
networks:
  default:
    external:
        name: cloudflare-tunnel